name: data
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none
# homepage: https://www.example.com

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  domain:
    path: ../lib_domain

  json_annotation: ^4.7.0
  freezed_annotation: ^2.2.0
  async: ^2.9.0

#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
  build_runner: ^2.3.0
  freezed: ^2.2.0
  json_serializable: ^6.5.1